name: Ping Streamlit App

on:
  schedule:
    - cron: "0 */2 * * *"  # Every 2 hours
  workflow_dispatch:        # Allows manual run from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl to keep Streamlit app awake
        run: |
            echo "Pinging Streamlit app..."
            curl -v https://ragtherepo.streamlit.app/
            echo "Ping completed."
